%% add_noise
% Add Gaussian or bursty noise to input image.

function noisy_image = add_noise(image, prefs, noise)
    if strcmp(noise.type, 'gaussian')
        if strcmp(prefs.image.type, 'bw')
            noisy_image = add_gaussian_noise( ...
                                image, ...
                                noise.bw.gaussian_std_dev, ...
                                noise.bw.gaussian_mean, ...
                                noise.bw.gaussian_confidence_interval ...
                            );
            
        else
            noisy_image = imnoise(image, ...
                                  'gaussian', ...
                                  noise.gaussian.mean, ...
                                  noise.gaussian.sigma);
        end
                          
    elseif strcmp(noise.type, 'burst')
        if strcmp(noise.bursty.type,'binary')
            noisy_image = add_bursty_noise(image, ...
                                           noise.bursty.correlation, ...
                                           noise.bursty.error, ...
                                           'binary');
        else
            noisy_image = add_bursty_noise(image, ...
                                           noise.bursty.correlation, ...
                                           noise.bursty.error, ...
                                           'gaussian', ...
                                           noise.bursty.mean, ...
                                           noise.bursty.sigma);
        end
        
    elseif strcmp(noise.type, 'both')
        if strcmp(prefs.image.type, 'bw')
            noisy_image = add_gaussian_noise( ...
                                image, ...
                                noise.bw.gaussian_std_dev, ...
                                noise.bw.gaussian_mean, ...
                                noise.bw.gaussian_confidence_interval ...
                            );
            
        else
            noisy_image = imnoise(image, ...
                                  'gaussian', ...
                                  noise.gaussian.mean, ...
                                  noise.gaussian.sigma);
        end
        
        if strcmp(noise.bursty.type,'binary')
            noisy_image = add_bursty_noise(noisy_image, ...
                                           noise.bursty.correlation, ...
                                           noise.bursty.error, ...
                                           'binary');
        else
            noisy_image = add_bursty_noise(noisy_image, ...
                                           noise.bursty.correlation, ...
                                           noise.bursty.error, ...
                                           'gaussian', ...
                                           noise.bursty.mean, ...
                                           noise.bursty.sigma);
        end
        
    else % no noise
        noisy_image = image;
    end
end